language: ruby
rvm:
- 2.4.0
bundler_args: --jobs=2
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle exec rails db:setup
  - bundle exec rspec
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.4"
deploy:
  provider: heroku
  api_key:
    secure: CG5ojF800bBz7tRXY8HJ2ct8zL2sFm7ERYcJL5fmYQjrqh5gNEQbxpuTBW1KvUcy/HbDf8T6Sj6tC35Az22A4N8yMni6ABfBKaqE5mVMmvFOLAUvZ6DVv+RmnbMHV7Ve/nGcg+yTUfmWSKCwrCsUyDeGxss5T3d5SyTMH4d9CvBDB8iB4KRly3H0E8fTFbeRgcqAJxwBMXE3GglHLxNW1ywuPRn3cF89PWSbbp4Uro0Z7KdwrLErQ3DcC9GQwO1//9+eN8Xd0IVTrZJlXPrSu4zo4YzTNxTLpyhwcsoJnzwjZo8COhu8WuST86o0ju2saQsk/PCeI9uANY9+ADFtuYHAEpy7BYZD5YTVkjD/rs8sUrH65OD1Kj4OfGrL+yGC7UJO3HhBE5Gyc3FtwZ++rJ5c7YSJHNGLk4W4ykZelbJQDIAtFNvjo6m7Oyug3Dhn4vQxAp9rsNIYijBW5mn3girAgk/i5q7yeI6KGn3ngmR9nl0d8Na9Ojh0lbiU1rSU71FvmjpwWQKjKHUjxDWYBDhbN3rNBhPOx++w+6EIWR/xJROnPKiDllUQOT0ZYM5KN3SHGe+TEXh1zPXAN8G3SZ90aH++7oOEdTl+0Q2F7vOE6u9iqMhLW1xvYqg/8Zs/FNnk+L3eBmER1RTVgj1s6sj800Yi+IxgVIlVJp7QRCc=
  app:
    master: sleepy-gorge-61199
  run: "rake db:migrate"
